---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 742945413490167808-C8QxRg0BIgqMS8ukkg39DXmu6nK2oFe
:access_token_secret: RRaDnhXbelkzoNRL3kedu8SBnMk7gHzvZl1RJNBUuTYbP
